log_output: ${FDC_LOG_DIR}

workflow:
  mailing:
    mail: true
    mailing_list: '/applications/asplm/asplmint/cust_root_dir/cdm_importer/fdc/piterion_maillist.txt'
  plmxml:
    move_from: '/mounts/import/cdm/VISVIEW/AS-PLM_fdc/'
    move_to: '/mounts/import/cdm/VISVIEW/AS-PLM/'
    move: true
  monitoring_path: '/applications/logs/fdc/monitoring'
  archive_path: '/applications/logs/fdc/archive'
  max_processes: 15
  simulate: true

fdc:
  file_download_client_home: ${FDC_HOME}
  environment_to_connect: 'PROD'
  # Uncomment the following for old credentials:
  # USERPID: 'pid5457'
  userpid: 'pid1489'
  credentials: ${FDC_CREDENTIALS_FILE}
  # credentials: '/applications/asplm/asplmint/security/fdc/encrypted_cred.txt'
  # Uncomment this line for production credentials:
  # CREDENTIALS: '/applications/asplm/asplmint/cust_root_dir/cdm_importer/fdc/secure/EncryptedCred_PROD.txt'
  xml_input_directory: ${FDC_CONF_DIR}
  # xml_input_directory: '/applications/asplm/asplmint/cust_root_dir/cdm_importer/fdc/input_config_RegressionTests'
  # xml_input_directory: '/applications/asplm/asplmint/cust_root_dir/cdm_importer/fdc/input_configs_test'
  # xml_input_directory: '/applications/asplm/asplmint/cust_root_dir/cdm_importer/fdc/testConfig/'
  status_check_interval: 1
  fdc_map: '/mounts/import/cdm/VISVIEW/MAP_fdc'
  java_path: ${JAVA_HOME}
  # java_path: '/applications/asplm/asplmint/java/jdk17/bin/'

