name: Ausrollen in INT
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags' 
jobs:
  deploy_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.TSERVER_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
          PATH_DEPLOY: ${{ vars.PATH_DEPLOY }}
        run: |
          echo $SERVER_IP
          echo "Deploying on server $SERVER_IP to the path $PATH_DEPLOY ... "
          #scp -i ${{ secrets.SSH_KEY }} -r ./* $SSH_USER@$SERVER_IP:$PATH_DEPLOY
          #ssh -i ${{ secrets.SSH_KEY }} $SSH_USER@$SERVER_IP "bash $PATH_DEPLOY/setup.sh"
