name: Ausrollen in T3
on:
  workflow_dispatch:
  
jobs:
  deploy_server:
    runs-on: [self-hosted, linux]
    #environment: T3
    env:
      TARGET_FOLDER: "/application/fdc/t3"
    steps:
      - name: Create Backup Directory
        run: |
          mkdir -p "$TARGET_FOLDER/Backup"

      - name: Archive Current Content (Excluding Backups)
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          BACKUP_PATH="$TARGET_FOLDER/Backup/archive_$TIMESTAMP.tar.gz"
          tar --exclude="$TARGET_FOLDER/Backup" -czf "$BACKUP_PATH" -C "$TARGET_FOLDER" .

      - name: Clean Up Old Backups
        run: |
          find "$TARGET_FOLDER/Backup" -type f -name "*.tar.gz" -mtime +7 -exec rm -f {} \;

      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          path: "$TARGET_FOLDER"
 

      #- name: Run the script
      #  run: |
      #    .${TARGET_DIR}/ManageFdc.sh  # Path to the shell script
