name: Ausrollen in T3
on:
  workflow_dispatch:
  
jobs:
  deploy_server:
    runs-on: [self-hosted, linux]
    #environment: T3
    env:
      TARGET_FOLDER: "/application/fdc/t3"
    steps:
      - name: Create Backup Directory
        run: |
          mkdir -p "$TARGET_FOLDER/Backup"

      - name: Archive Current Content (Excluding Backups)
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          BACKUP_PATH="$TARGET_FOLDER/Backup/archive_$TIMESTAMP.tar.gz"
          tar --exclude="$TARGET_FOLDER/Backup" --exclude="$TARGET_FOLDER/Backup/*" --exclude="$TARGET_FOLDER/.*" -czf "$BACKUP_PATH" -C "$TARGET_FOLDER" .
          echo "Backup file: $BACKUP_PATH"

      - name: Clean Up Old Backups
        run: |
          find "$TARGET_FOLDER/Backup" -type f -name "*.tar.gz" -mtime +3 -exec rm -f {} \;
      
      - name: Clean target folder excluding "Backup" and its content
        run: |
          find "$TARGET_FOLDER" -mindepth 1 -maxdepth 1 ! -name "Backup" -exec rm -rf {} +

      - name: Set target folder environment variable
        run: echo "$TARGET_FOLDER" >> $GITHUB_ENV
        
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          path: ${{ env.TARGET_FOLDER }}

      - name: Set Script Permissions
        run: |
          SCRIPT_DIR="scripts"
          SCRIPT_NAME="ManageFdc.sh"
          chmod +x "$TARGET_FOLDER/$SCRIPT_NAME"
          echo "Execution permissions set for $TARGET_FOLDER/$SCRIPT_NAME"

      #- name: Run the script
      #  run: |
      #    .${TARGET_DIR}/ManageFdc.sh  # Path to the shell script
